# Generated by Django 5.2.6 on 2025-09-16 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(max_length=8, unique=True)),
                ('turf_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=200)),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('06:00-08:00', '06:00-08:00'), ('08:00-10:00', '08:00-10:00'), ('10:00-12:00', '10:00-12:00'), ('12:00-14:00', '12:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'turf_db',
            },
        ),
    ]
