# Generated by Django 5.2.6 on 2025-09-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfbooking',
            name='booking_code',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
    ]
